### ISSUE TITLE
3.2.0-beta Known Issues & Suggestions.

### ISSUE THREAD

**Issue by RChestnut** [Nexusoft/NexusInterface#260]
![Image](https://github.com/user-attachments/assets/16beb6cc-2861-42e8-ac7f-7475a5810179)

My wallet version is <code>3.2.0-alpha.0</code> on Windows 10 x64, with remote core running on ARM64.
(The version of remote core is <code>5.1.5-rc14-9 Tritium++ CLI [LLD]{ARM aarch64]</code>)

### `Known Issues`
1. Multiple 'Pre-Release Active' notification shows.

![Image](https://github.com/user-attachments/assets/1582316a-6fbb-4e65-8c4f-54c92fdb69cf)

- After start, It appears twice. May seems that caused by event miscatch.
- `Expected behavior` : Should show only once, or add 'Do not show this window later' button may helps not making bothering.

2. Cannot disable 'sending using data as anonymous.'
- Yes, I know that is alpha build, But i think that you should give a notice about collecting information on the EULA, Also that should be changeable option for rejecting collection.
- It may cause the privacy issue. (or may this is overthinking.)
- But when i press the button for turning off the option, the 'Pre-Release Active' notification shows, Also option is not being changed.
- `Expected behavior` : Should make the button modifiable, Also should add the information on the EULA about collecting information with collecting range

3. The modules not working and installing.

![Image](https://github.com/user-attachments/assets/5ea83b6a-9a05-4892-aee5-e4c267c46b61)

- Failed initializing all of modules; Even this modules had worked on 3.1.4.

![Image](https://github.com/user-attachments/assets/2e9ef9b5-36fe-493b-b80f-71a5c48976bd)

- Also it shows <code>'The "path" argument must be of type string. Received undefined'</code>, When i install these modules.
- Seems that the argument encounters type mismatch or the parameter cannot be handled.
- `Expected behaviour` : Because it cannot load the modules that had been already installed, Seems that the address value had been mismatched or miscasted. The 'path' parameter should be parsed.

4. The lock screen goes 'blank' after unlock or input the wrong password.

![Image](https://github.com/user-attachments/assets/de79c511-a816-4da5-813d-97f2cf227d44)

- Seems that the related bug had reported on #245, but i think that it hadn't been fixed.
- The window goes blank after press unlock, Neither it goes when the password is inputted nor not, Even the correct password is inputted or not.
- `Expected behaviour` : Makes error on inputting wrong password. Blank input makes button being disabled. Only should be unlocked on proper password.

### `Suggestion`
- For showing market data on the main page, It would be great that showing origin of market data. I know that it shows market data of the market that has higher daily trading volume, But the users don't know where these are from with only see the main page until they search the market.

**Comment by RChestnut** [comment]
`Update On 3.2.0-beta`

1. Multiple 'Pre-Release Active' notification shows. - Not Fixed.
2. Cannot disable 'sending using data as anonymous.' - Not Fixed, Yet
3. Failed initializing all of modules; Even this modules had worked on 3.1.4. - Humm.....

![Image](https://github.com/user-attachments/assets/a9660af7-4fb9-49b3-91ea-149a4a66cfd7)

Modules shows correctly, Showing update available also correctly, But when i press the update button.....

![Image](https://github.com/user-attachments/assets/27b1a243-227f-4f7c-8597-57a4998001b3)
`Cannot find module archive file among assets` error encounts.
Seems that does module package delivery system not working properly...?

![Image](https://github.com/user-attachments/assets/0c90f747-5ddd-4a21-83c7-226a173b1faa)

![Image](https://github.com/user-attachments/assets/fd6eb9bf-9db2-4780-ae5b-3d0bce119587)

Also i can see the buttons of installed modules on the dock, But when i press these buttons, It shows nothing....

`ADD`

![Image](https://github.com/user-attachments/assets/7dcbe63e-3255-49aa-b9c6-9237b10bc845)

![Image](https://github.com/user-attachments/assets/a95071bf-40e7-4362-8861-770bbba5a1a0)

After i overwrote these module with new version, it works now.

Seems that there are some problems on migration and package delivery system(especially).
When i try to update the wallet to beta, it only shows `'there's a new version available'` and only `'downloading'` notification, But nothing happens. 
Maybe seems that there's also problem with package delivery system since in alpha version.

4. The lock screen goes 'blank' after unlock or input the wrong password. - FIXED!

![Image](https://github.com/user-attachments/assets/778954c7-401f-46dd-a615-6f9917b1de76)

![Image](https://github.com/user-attachments/assets/1b24e451-024f-40e9-9dcc-13ccf423496f)

Working as flawlessly.

**Comment by Qrysto** [comment]
These issues will be fixed on the next release

**Comment by RChestnut** [comment]
> These issues will be fixed on the next release

Great, I'm gonna close this issue as solved after testing it when it releases.
